### ISSUE TITLE
I'm newby 

### ISSUE THREAD

**Issue by VIPspawn** [KellanHiggins/UnityFBXExporter#13]
Sorry, not understand how to use this tool. I have not used unity before and  i don't know how to export it after I've selected the object. I could not find the tool menus. :(

**Comment by KellanHiggins** [comment]
No problemo! Should be under Assets/FBX Exporter.

**Comment by ahunter16** [comment]
I'd just like to add that he means the Assets dropdown menu at top of the screen and not the Assets folder! It seems obvious now, but I spent a few minutes scratching my head at that one!

**Comment by KellanHiggins** [comment]
@VIPspawn I've also exports to the dropdown menu in the scene view because that is where I kept trying to add it from. Hope that works!
