### ISSUE TITLE
Don't lie me! Where is goal??????????????????

### ISSUE THREAD

**Issue by sourceskyboxer** [KellanHiggins/UnityFBXExporter#18]
Hello I am mad because your tutorial I don't understand how do I select gameobject i have selected. than where is select any type of export????????????????

![stepto_exportfbx](https://cloud.githubusercontent.com/assets/3496136/22611838/331418c4-ea6d-11e6-9923-9fa38cb10220.JPG)

I can not find that... where is i like that?

**Comment by KellanHiggins** [comment]
Hey, absolutely no reason to get mad. Look under Assets -> FBX Exporter. The options will be there. I will add this to the tutorial next time I update this.

**Comment by sourceskyboxer** [comment]
Thanks my dear I am sorry for that. :) your right

**Comment by KellanHiggins** [comment]
Haha no problem. I am dumb for leaving out such an important step anyways. :P.
