### ISSUE TITLE
FBX file exported with 0 verts, 0 tris

### ISSUE THREAD

**Issue by Danand** [KellanHiggins/UnityFBXExporter#19]
Hi there!

I've tried to check exported .fbx in Unity and nothing appears (0 verts, 0 tris). 3ds Max crashes while importing this .fbx.

Unity version: 5.5.0p4.
Exported .fbx file: [Unity primitive sphere](https://dl.dropboxusercontent.com/u/111424884/Sphere.fbx).

**Comment by KellanHiggins** [comment]
Hmmm, could be the new Unity. You are exporting the grey sphere that Unity provides?

I haven't tested this on Unity 5.5 yet. Its probably crashing because the file hasn't been written correctly. I glanced over the file you posted and it looks fine.

Have you tried this in Unity 5.4?

**Comment by Danand** [comment]
`Have you tried this in Unity 5.4?`
No. Just 5.5.
`You are exporting the grey sphere that Unity provides?`
Yep.

**Comment by KellanHiggins** [comment]
Crap, this slipped off my list of things to do. I assume you haven't got this fixed right?

**Comment by KellanHiggins** [comment]
Tried exporting the sphere on Unity 5.5 and it was fine. Can you try again with the new changes?
