### ISSUE TITLE
Is the exported FBX ASCII or binary?

### ISSUE THREAD

**Issue by Zireael07** [KellanHiggins/UnityFBXExporter#24]
See title.

**Comment by mikelortega** [comment]
ASCII, read the description:
A tool to export any Unity GameObject into a FBX ASCII format.

**Comment by KellanHiggins** [comment]
Hmm, maybe not super clear. It mentions this under the "export to blender" part. I'll make sure to include this more prominently in the readme later.

**Comment by Thane5** [comment]
The readme mentions a converter, where can i download it?

**Comment by KellanHiggins** [comment]
Look up Autodesk FBX Converter. Should be the 2013 version :).
