### ISSUE TITLE
Is it impossible to save animated model as FBX file?

### ISSUE THREAD

**Issue by Mose726** [KellanHiggins/UnityFBXExporter#25]
I appreciate your work very much.
I would like to export fbx files of model which is animated according to data came from motion capture system.
I tried exporting fbx file while animating the model, but those exported fbx files were the same models with same posture (original T-pose).

Do you have any idea to deal with this issue?
Thank you.

**Comment by KellanHiggins** [comment]
Oh boy, this is a heck of a complicated problem. I haven't looked at all how the animation information is store in FBX files.

If you figure it out, let us know. I would love to include that in this project.

To start off, I would find a FBX which has animation, convert it to ASCII and look through the file to see where the animation information is stored.

**Comment by KellanHiggins** [comment]
I have decided to not include animation as part of this exporter. If someone writes it and contributes that is great, but it is fairly complex to do this AND Unity's own FBX exporter does it.
