### ISSUE TITLE
If a GameObject doesn't have a mesh and no children with meshes, disregard

### ISSUE THREAD

**Issue by KellanHiggins** [KellanHiggins/UnityFBXExporter#3]
This will fill an FBX file with empty GameObjects that have no meshes in them. Should not include those in the fbx file.

**Comment by MattOstgard** [comment]
This should probably be an option with the trimming empties being on by default. There are cases where the node might be important to the user. For instance: if a user has placed a bunch of lights in Unity and wants to bring the scene over to Blender then they can at the very release replace all of those nodes with Blender lights.

**Comment by KellanHiggins** [comment]
I now think we shouldn't trim empties. If they want to export empty stuff, let 'em do it! Thanks :)
