### ISSUE TITLE
Exporting at Runtime

### ISSUE THREAD

**Issue by curiousbrandon** [KellanHiggins/UnityFBXExporter#30]
First of all, thanks for the exporter! It works great in the editor. I am trying to export at runtime. In the readme it says "Sort of works at Runtime. Needs to use File.IO instead of AssetDatabase to truly work at runtime." - any suggestions where I should look and begin to modify for this to work at runtime? 

Thanks again!

**Comment by theBrandonWu** [comment]
Yeah I got runtime FBX exporting working in https://www.pepwuper.com/portfolio/curious-blocks-augmented-reality-creative-app/ (app not currently available for download).

**Comment by theBrandonWu** [comment]
Basically just did this:

`UnityFBXExporter.FBXExporter.ExportGameObjToFBX(exportedGO,filePath,false,false);`

**Comment by KellanHiggins** [comment]
I am pretty sure I made some updates at some point to ensure it would work at runtime. But not entirely sure. Let me know if you have any problems :).

**Comment by pentti3d** [comment]
I just got this working at runtime, and to export textures too. Some of the original premises might got lost at the same time, but everything I need right now should work (only some testing made).

I had to remove everything under the UnityEditor namespace. All AssetDatabase usage was of course removed, the textures are copied from object material's texture to RenderTexture using Graphics.Blit, and then a new .png export texture file is created using Texture2D -> byte[] -> File.WriteAllBytes. Texture's name comes directly from object material's texture, to be written to texture linking lines in the resulting FBX.

This method is also a lot faster than copying textures through filesystem using AssetDatabase (in the editor, where original method works). Writing this quick and dirty fix took about a full working day, but a more comprehensive and pretty version would take more time. So I won't release my modified version, instead using these guidelines everyone may start their own modifications for their use cases.

**Comment by guoguoguilai** [comment]
> I just got this working at runtime, and to export textures too. Some of the original premises might got lost at the same time, but everything I need right now should work (only some testing made).
> 
> I had to remove everything under the UnityEditor namespace. All AssetDatabase usage was of course removed, the textures are copied from object material's texture to RenderTexture using Graphics.Blit, and then a new .png export texture file is created using Texture2D -> byte[] -> File.WriteAllBytes. Texture's name comes directly from object material's texture, to be written to texture linking lines in the resulting FBX.
> 
> This method is also a lot faster than copying textures through filesystem using AssetDatabase (in the editor, where original method works). Writing this quick and dirty fix took about a full working day, but a more comprehensive and pretty version would take more time. So I won't release my modified version, instead using these guidelines everyone may start their own modifications for their use cases.

What about the material？ Is it possible to export material at runtime？

**Comment by Alby90** [comment]
> I just got this working at runtime, and to export textures too. Some of the original premises might got lost at the same time, but everything I need right now should work (only some testing made).
> 
> I had to remove everything under the UnityEditor namespace. All AssetDatabase usage was of course removed, the textures are copied from object material's texture to RenderTexture using Graphics.Blit, and then a new .png export texture file is created using Texture2D -> byte[] -> File.WriteAllBytes. Texture's name comes directly from object material's texture, to be written to texture linking lines in the resulting FBX.
> 
> This method is also a lot faster than copying textures through filesystem using AssetDatabase (in the editor, where original method works). Writing this quick and dirty fix took about a full working day, but a more comprehensive and pretty version would take more time. So I won't release my modified version, instead using these guidelines everyone may start their own modifications for their use cases.

My issue is linking the correct texture to the FBX after that i have exported them. Can you share your script?

**Comment by KalaniSamarathunga** [comment]
> Yeah I got runtime FBX exporting working in https://www.pepwuper.com/portfolio/curious-blocks-augmented-reality-creative-app/ (app not currently available for download).

Can you please share the source code here?

**Comment by KellanHiggins** [comment]
Yeah I would love to see that!

**Comment by Nielstupido** [comment]
> I just got this working at runtime, and to export textures too. Some of the original premises might got lost at the same time, but everything I need right now should work (only some testing made).
> 
> I had to remove everything under the UnityEditor namespace. All AssetDatabase usage was of course removed, the textures are copied from object material's texture to RenderTexture using Graphics.Blit, and then a new .png export texture file is created using Texture2D -> byte[] -> File.WriteAllBytes. Texture's name comes directly from object material's texture, to be written to texture linking lines in the resulting FBX.
> 
> This method is also a lot faster than copying textures through filesystem using AssetDatabase (in the editor, where original method works). Writing this quick and dirty fix took about a full working day, but a more comprehensive and pretty version would take more time. So I won't release my modified version, instead using these guidelines everyone may start their own modifications for their use cases.

Can you share us your code?

**Comment by KellanHiggins** [comment]
I am very close to adding exporting at runtime into this repo. Please bug me if this isn't out in a month.
