### ISSUE TITLE
Exporter exports empty meshes when used with Unity 2017.3.0f3 (64 bit)

### ISSUE THREAD

**Issue by LasseWestmark** [KellanHiggins/UnityFBXExporter#31]
It prints no errors, opening the fbx in 3ds max crashes max.

Works fine in Unity 5.6.3p3 (64 bit)

**Comment by KellanHiggins** [comment]
Uh oh. Have you tried with a bunch of different objects? Can you send me the file that was exported?

**Comment by srktnc** [comment]
i'm having the same problem. help me please

**Comment by KellanHiggins** [comment]
@srktnc Can you send me the file that was exported? Also is 2017.3 required? I don't think that version is even supported by Unity anymore. I see they are continuing support of 2017.4, but 2017.3 is missing from their install list.

**Comment by srktnc** [comment]
i use unity 2019.1
file : https://www21.zippyshare.com/v/jyBVegpw/file.html

**Comment by KellanHiggins** [comment]
Can you please send me the exported file instead? Are you using Mac or PC? I think there may be an issue with Mac VS adding some non-appearing characters at the start of every file. It caused me big headaches when trying to commit on Mac.

**Comment by srktnc** [comment]
used pc .
Thanks for your interest .

**Comment by KellanHiggins** [comment]
Hi, I am unable to help you @srktnc if you don't send me your fbx ASCII file.
