### ISSUE TITLE
Path Error

### ISSUE THREAD

**Issue by yixingDBJ** [KellanHiggins/UnityFBXExporter#36]
Hello, My Unity Tips  UnauthorizedAccessException: Access to the path 'D:\' is denied.

**Comment by KellanHiggins** [comment]
Sounds like you can't write to your D drive in this case.

**Comment by yixingDBJ** [comment]
Yes, but how to solve it? This problem will only appear when importing materials and maps

**Comment by yixingDBJ** [comment]
![图片](https://user-images.githubusercontent.com/44353513/70198175-16c0b180-1749-11ea-9c26-fcb6e4c54b54.png)

**Comment by KellanHiggins** [comment]
I don't think this is an exporter problem. Unity isn't allowed to write to the D: drive in this case. Can you export it to the C drive?
