### ISSUE TITLE
Skinned meshes only output with one material "No Name" 

### ISSUE THREAD

**Issue by red1134** [KellanHiggins/UnityFBXExporter#37]
Unity 2018.4.20f1
Reproduce - Take any humanoid model with an armature and skinned mesh. Exporting with any of the options gives same results. FBX with a single material and no way of restoring the lost materials.

**Comment by KellanHiggins** [comment]
Whoops, guess I didn't make it clear that Skinned Mesh Renderers are definitely not supported by the FBX exporter. I THINK the FBX exporter that Unity made at some point may be able to do it.

I'll leave this open until I put a readme update .

**Comment by KellanHiggins** [comment]
I've added a thing to the readme. Sorry this project can't support skinned mesh armatures. But that stuff is complex!

**Comment by red1134** [comment]
The Unity one does in fact support it but it is sometimes buggy and gets mysterious errors that I cannot solve which resulted in me turning to your script as a possible solution. I found that exporting parts of a model separately sometimes fixes the issue and then I can re-combine in them in Blender. Thank you though anyways for clarifying. I still use your script occasionally for simple mesh export. Great work on it!

**Comment by KellanHiggins** [comment]
Appreciate the support! Yeah this isn't the greatest exporter ever, just basically writing to a text file but it does the job for simple stuff. Maybe someone will add exporting skinned meshes some day...
