### ISSUE TITLE
Exports (mostly) empty meshes - indices out of range

### ISSUE THREAD

**Issue by luisdiogo98** [KellanHiggins/UnityFBXExporter#38]
Hi!

I'm trying to export meshes out of a project with Unity 2019.3.0f6. No matter what object I export (including any default unity meshes), it gives the same three warnings:

Mesh contains 24 vertices for 0 colors. Skip color export
Mesh indices of Cube are out of range!
Mesh indices of Cube are out of range!

and the mesh comes out mostly empty (how many vertices are actually exported depend on the mesh). I checked them both on Unity and Blender (in Blender after I ran them through the Autodesk FBX Converter). 

Here are two of the generated files, one for the default Unity cube and another for the object I was actually trying to export.
[meshes.zip](https://github.com/KellanHiggins/UnityFBXExporter/files/4662153/meshes.zip)

Thanks!

**Comment by KellanHiggins** [comment]
Can I take a wild stab and say that in your country you use commas instead of periods to denote decimals?

**Comment by KellanHiggins** [comment]
Can you check it now with the latest release. I've added the internationalization for everyone who uses commas instead of periods for non full numbers.

**Comment by luisdiogo98** [comment]
That fixed it. Thanks!

**Comment by KellanHiggins** [comment]
Perfect! I fixed it a few weeks back for Building Crafter but you pushed me to upload it here. Thanks!
