### ISSUE TITLE
Is it possible to export weightpainting?

### ISSUE THREAD

**Issue by guiglass** [KellanHiggins/UnityFBXExporter#40]
Hello, Thanks for creating this plugin! 

I was wondering if it would be possible to include weightpaint with the exported .fbx?

**Comment by KellanHiggins** [comment]
Unfortunately this is way beyond the scope of this plugin. I wonder if Unity's implementation has this. Skinned Mesh renderers are an entirely different beast and I have no idea how they are written to an FBX.
