### ISSUE TITLE
Unable to export line renderer comoonent

### ISSUE THREAD

**Issue by ruchirnaphade** [KellanHiggins/UnityFBXExporter#41]
Hello, Thanks a lot for this package. I have one question, I am instantiating my own prefabs and attaching it to my .fbx model. These prefabs are like MRTK's Tooltip prefab which has a line rendered component which draws a line to show the tooltip for the object. With this package, everything works fine except I can not see the line renderer component in the exported .fbx file. In other words, I am not able to export the line renderer's line. Could you please tell me is it possible to do this? 

PS: I am relatively new to Unity/AR field and trying to learn by my own. Any kind of help would be appreciated. I am trying to use this package through the script while running my scene by calling export functions on clicking buttons. 

Sorry for the trouble.

**Comment by KellanHiggins** [comment]
Line Renderers are not meshes. They are some other thing that uses a shader to render it. Unless you can convert the line renderer to a flat quad, it isn't going to export unfortunately. I am not sure how you would do this :(.

**Comment by ruchirnaphade** [comment]
> 
> 
> Line Renderers are not meshes. They are some other thing that uses a shader to render it. Unless you can convert the line renderer to a flat quad, it isn't going to export unfortunately. I am not sure how you would do this :(.

Hello Kellan, thanks a lot for the reply. I just wanted to know the reason for it.
