### ISSUE TITLE
Please update version 1.3.0 to the latest 1.6.0

### ISSUE THREAD

**Issue by FecTu** [KellanHiggins/UnityFBXExporter#42]

**Comment by KellanHiggins** [comment]
I am unclear what you are talking about, there is no version 1.6.0 since I made this exporter!

**Comment by FecTu** [comment]
Well, what versions of unity does the export work on?

**Comment by KellanHiggins** [comment]
Should work on all versions. 2017 to the latest. Let me know if it doesn't work on a newer version of Unity.
