### ISSUE TITLE
iOS and Android support

### ISSUE THREAD

**Issue by TheThijs** [KellanHiggins/UnityFBXExporter#43]
Hi! Does the exporter support mobile standalone builds like iOS and Android?

**Comment by KellanHiggins** [comment]
I am not sure. It simply writes to an ASCII fbx file with a lot of manual string building. There is nothing fancy so it probably works. I am not sure what the application would be since it is designed to work within Unity's editor.

**Comment by TheThijs** [comment]
I just found out it works fine on iOS. It was a little bit of a search but the .fbx files are being saved under /var/mobile/Containers/Data. Thanks for the reply!

**Comment by KellanHiggins** [comment]
Awesome, glad to hear it :).
