### ISSUE TITLE
Is it possible to export with point cloud shader?

### ISSUE THREAD

**Issue by stars66** [KellanHiggins/UnityFBXExporter#44]
Hi I'm using point cloud shader (jp.keijiro.pcx) to render mesh for AR scene. Is it possible to export? Thanks in advance.

**Comment by KellanHiggins** [comment]
I'd say give it a shot. If the render mesh is a standard PBR shader, should be fine.

**Comment by stars66** [comment]
Failed getting triangles. Submesh topology is lines or points.

**Comment by KellanHiggins** [comment]
I am not too clear how the pointmesh is stored which may be why you are having issues. I believe it only export vertexes and triangles. Its supposed to be a simple exporter, you may be out of luck.
