### ISSUE TITLE
FBX doesn't export with skin rigging and bones

### ISSUE THREAD

**Issue by Lilothestitch16** [KellanHiggins/UnityFBXExporter#57]
When I export model as FBX, it doesn't export the rigging.
[FBX.zip](https://github.com/KellanHiggins/AsciiFBXExporterForUnity/files/15285726/FBX.zip)

**Comment by KellanHiggins** [comment]
Sadly I never got around to implementing rigging in this. It's under point 6 of known limitations in the readme. If you do want to implement that I would be happy to accept a pull request.
